type: Task
features:
  container:
    other: 
      tasks:
        path: 2
        comparator: right-down
  contents:
    self: 
      agent:
        path: 1
doc-ref: tasks/reporting.md
configuration:
  configuration: |
    description: >
      Review the context you got and expand each topic into a full section for a report.
      Make sure the report is detailed and contains any and all relevant information.
    expected_output: >
      A fully fledge reports with the mains topics, each with a full section of information.
      Formatted as markdown without '```'
